### ISSUE TITLE
Team assignment

### ISSUE THREAD

**Issue by erfanio** [unihackhq/skilled-acolyte-backend#23]
Have endpoints for team assignment

- [x] Endpoint to get student's team
- [x] Endpoint to get student's team invitations
- [x] invite a student to a team
- [x] leave team (maybe if we have time)

@kochie @terencehuynh any more?

**Comment by terencehuynh** [comment]
This has been resolved as part of PR #30

**Comment by erfanio** [comment]
@terencehuynh are we not doing leaving team?

**Comment by erfanio** [comment]
We need a leave endpoint
