### ISSUE TITLE
Access JWT's userId in handlers

### ISSUE THREAD

**Issue by erfanio** [unihackhq/skilled-acolyte-backend#33]
@hugomd is this possible?

**Comment by hugomd** [comment]
@erfanio The decoded JWT is available in every request (that has authentication) via `request.auth.credentials`.

**Comment by erfanio** [comment]
😅 haha sorry

**Comment by hugomd** [comment]
@erfanio Don't be sorry! The hapi docs need some work, IMO, a lot of stuff isn't self-evident.
