### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by erfanio** [unihackhq/skilled-acolyte-backend#64]
- [x] Schedule (Automatic)
- [ ] Manual - custom message
  - [ ] Opening schedule in app
  - [ ] Opening somewhere else? (suggestions @dsykesturner )

Notifications to enable/disable
- sessions
- tech talks
- lunch, dinner, etc
- manual from unihack team

**Comment by erfanio** [comment]
Like when you click the notification, it's gonna open the app to the schedule screen

**Comment by dsykesturner** [comment]
Sorry for the late reply. No I wouldn't worry about opening specific screens. App side I might not have time to implement
